// Knowledge base loader. Source of truth: /kb/*.md + /kb/_meta.json (English).
// Per-language overrides live at /kb/{lang}/*.md + /kb/{lang}/_meta.json
// and are generated by scripts/translate-kb-bulk.ts.
import metaRaw from "/kb/_meta.json?raw";
import type { LanguageCode } from "@/contexts/LanguageContext";

export type TopicMeta = {
  slug: string;
  title: string;
  category: string;
  /** Section name as cited in chat replies, e.g. "Burns" or "Anaphylaxis". */
  section: string;
  summary: string;
  keywords: string[];
  related: string[];
};

type LangMeta = {
  language: string;
  categories: Record<string, string>;
  topics: Array<{ slug: string; title: string; summary: string }>;
};

// English bodies
const enBodies = import.meta.glob("/kb/*.md", {
  query: "?raw",
  import: "default",
  eager: true,
}) as Record<string, string>;

// All translated bodies, keyed by `/kb/{lang}/{slug}.md`
const langBodies = import.meta.glob("/kb/*/*.md", {
  query: "?raw",
  import: "default",
  eager: true,
}) as Record<string, string>;

// Per-language meta files
const langMetaRaw = import.meta.glob("/kb/*/_meta.json", {
  query: "?raw",
  import: "default",
  eager: true,
}) as Record<string, string>;

const langMetaByCode: Record<string, LangMeta> = {};
for (const [path, raw] of Object.entries(langMetaRaw)) {
  const m = path.match(/\/kb\/([^/]+)\/_meta\.json$/);
  if (m) {
    try {
      langMetaByCode[m[1]] = JSON.parse(raw);
    } catch {
      /* ignore malformed */
    }
  }
}

const enTopics: TopicMeta[] = (JSON.parse(metaRaw) as TopicMeta[])
  .slice()
  .sort((a, b) => a.title.localeCompare(b.title));

export const topics: TopicMeta[] = enTopics;

export const categories: string[] = Array.from(
  new Set(topics.map((t) => t.category)),
).sort();

/** Topics for a given language (uses translated title/summary when available). */
export function topicsFor(lang: LanguageCode = "en"): TopicMeta[] {
  if (lang === "en") return enTopics;
  const lm = langMetaByCode[lang];
  if (!lm) return enTopics;
  const trBySlug = Object.fromEntries(lm.topics.map((t) => [t.slug, t]));
  const catMap = lm.categories || {};
  return enTopics
    .map((t) => {
      const tr = trBySlug[t.slug];
      return {
        ...t,
        title: tr?.title || t.title,
        summary: tr?.summary || t.summary,
        category: catMap[t.category] || t.category,
      };
    })
    .sort((a, b) => a.title.localeCompare(b.title));
}

export function getTopic(slug: string, lang: LanguageCode = "en"): TopicMeta | undefined {
  return topicsFor(lang).find((t) => t.slug === slug);
}

export function getBody(slug: string, lang: LanguageCode = "en"): string {
  if (lang !== "en") {
    const k = `/kb/${lang}/${slug}.md`;
    if (langBodies[k]) return langBodies[k];
  }
  return enBodies[`/kb/${slug}.md`] ?? "";
}

export function topicsByCategory(lang: LanguageCode = "en"): Record<string, TopicMeta[]> {
  const out: Record<string, TopicMeta[]> = {};
  for (const t of topicsFor(lang)) {
    (out[t.category] ||= []).push(t);
  }
  return out;
}

/** Match a free-form section name to a KB slug (uses English metadata). */
export function findTopicBySection(name: string): TopicMeta | undefined {
  const n = name.trim().toLowerCase().replace(/\([^)]*\)/g, "").trim();
  if (!n) return undefined;
  const exact = enTopics.find((t) => t.section.toLowerCase() === n);
  if (exact) return exact;
  const byTitle = enTopics.find((t) => t.title.toLowerCase() === n);
  if (byTitle) return byTitle;
  const sub = enTopics.find(
    (t) =>
      n.includes(t.section.toLowerCase()) ||
      t.section.toLowerCase().includes(n) ||
      t.title.toLowerCase().includes(n),
  );
  if (sub) return sub;
  return enTopics.find((t) =>
    t.keywords.some((k) => n.includes(k.toLowerCase())),
  );
}

/**
 * Score topics against a free-form chat text (user question + assistant reply)
 * and return the best match if its score clears a confidence threshold.
 * Uses English metadata for matching — works across all languages because the
 * AI's responses tend to include English medical terms.
 */
export function findBestTopic(text: string, minScore = 4): TopicMeta | undefined {
  const t = text.toLowerCase();
  if (t.length < 8) return undefined;
  let best: { topic: TopicMeta; score: number } | undefined;
  for (const topic of enTopics) {
    let score = 0;
    const title = topic.title.toLowerCase();
    const section = topic.section.toLowerCase();
    // Whole-word title/section matches are strong signals
    const titleRe = new RegExp(`\\b${escapeRe(title)}\\b`, "i");
    const sectionRe = new RegExp(`\\b${escapeRe(section)}\\b`, "i");
    if (titleRe.test(t)) score += 5;
    else if (t.includes(title)) score += 3;
    if (section !== title) {
      if (sectionRe.test(t)) score += 4;
      else if (t.includes(section)) score += 2;
    }
    for (const kw of topic.keywords) {
      const k = kw.toLowerCase();
      if (k.length < 3) continue;
      const re = new RegExp(`\\b${escapeRe(k)}\\b`, "i");
      if (re.test(t)) score += 2;
    }
    if (!best || score > best.score) best = { topic, score };
  }
  if (!best || best.score < minScore) return undefined;
  return best.topic;
}

/**
 * Return related topic slugs for a given slug, expanded with topics that share
 * the same category or overlapping keywords. Capped at `max` (default 6).
 */
export function relatedSlugs(slug: string, max = 6): string[] {
  const base = enTopics.find((t) => t.slug === slug);
  if (!base) return [];
  const chosen: string[] = [...(base.related || [])];
  const has = new Set(chosen);
  has.add(slug);
  const kw = new Set(base.keywords.map((k) => k.toLowerCase()));
  const scored = enTopics
    .filter((t) => !has.has(t.slug))
    .map((t) => {
      let s = 0;
      if (t.category === base.category) s += 2;
      for (const k of t.keywords) if (kw.has(k.toLowerCase())) s += 3;
      return { slug: t.slug, s };
    })
    .filter((x) => x.s > 0)
    .sort((a, b) => b.s - a.s);
  for (const x of scored) {
    if (chosen.length >= max) break;
    chosen.push(x.slug);
    has.add(x.slug);
  }
  return chosen.slice(0, max);
}

function escapeRe(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/**
 * Auto-link the first mention of other topics inside a markdown body.
 * Skips code blocks, headings, blockquotes, table separators, and lines
 * that already contain markdown links. `hrefFor` builds the link target.
 */
export function autoLinkBody(
  body: string,
  currentSlug: string,
  lang: LanguageCode,
  hrefFor: (slug: string) => string,
): string {
  const others = topicsFor(lang).filter((t) => t.slug !== currentSlug);
  const en = enTopics.filter((t) => t.slug !== currentSlug);
  // Build list of {term, slug} from both localized + English titles/sections,
  // longest first to prefer multi-word matches.
  const seen = new Set<string>();
  const terms: Array<{ term: string; slug: string }> = [];
  const push = (term: string | undefined, slug: string) => {
    if (!term) return;
    const t = term.trim();
    if (t.length < 4) return;
    const key = `${slug}::${t.toLowerCase()}`;
    if (seen.has(key)) return;
    seen.add(key);
    terms.push({ term: t, slug });
  };
  for (const t of others) {
    push(t.title, t.slug);
    push(t.section, t.slug);
  }
  for (const t of en) {
    push(t.title, t.slug);
    push(t.section, t.slug);
  }
  terms.sort((a, b) => b.term.length - a.term.length);

  const usedSlugs = new Set<string>();
  let inFence = false;
  const lines = body.split("\n");
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (/^\s*```/.test(line)) {
      inFence = !inFence;
      continue;
    }
    if (inFence) continue;
    if (/^\s*(#|>|\||!\[)/.test(line)) continue;
    if (/\]\([^)]+\)/.test(line)) continue; // already contains a link
    let out = line;
    for (const { term, slug } of terms) {
      if (usedSlugs.has(slug)) continue;
      const re = new RegExp(`(?<![\\w\\[/])(${escapeRe(term)})(?![\\w\\]])`, "i");
      if (re.test(out)) {
        out = out.replace(re, `[$1](${hrefFor(slug)})`);
        usedSlugs.add(slug);
      }
    }
    lines[i] = out;
  }
  return lines.join("\n");
}

/**
 * Wrap phone numbers in markdown `tel:` links so they become tappable on mobile.
 * Skips code fences, headings, table separators, and text already inside a link.
 */
const PHONE_RE = /(?<![\w/])(\+?\d[\d\s().-]{2,}\d)(?![\w])/g;

export function autoLinkPhones(body: string): string {
  let inFence = false;
  const lines = body.split("\n");
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (/^\s*```/.test(line)) {
      inFence = !inFence;
      continue;
    }
    if (inFence) continue;
    if (/^\s*(#|\|)/.test(line)) continue;

    // Walk the line, skipping segments inside existing markdown links [text](url).
    const out: string[] = [];
    let idx = 0;
    const linkRe = /\[[^\]]*\]\([^)]*\)/g;
    let m: RegExpExecArray | null;
    while ((m = linkRe.exec(line)) !== null) {
      out.push(replacePhonesInSegment(line.slice(idx, m.index)));
      out.push(m[0]);
      idx = m.index + m[0].length;
    }
    out.push(replacePhonesInSegment(line.slice(idx)));
    lines[i] = out.join("");
  }
  return lines.join("\n");
}

function replacePhonesInSegment(seg: string): string {
  return seg.replace(PHONE_RE, (match) => {
    const digits = match.replace(/[^\d+]/g, "");
    const d = digits.replace(/^\+/, "");
    if (d.length < 3 || d.length > 15) return match;
    // Skip 4-digit numbers that look like years (1900-2099) — too noisy.
    if (d.length === 4 && /^(19|20)\d{2}$/.test(d)) return match;
    return `[${match}](tel:${digits})`;
  });
}
