import { describe, it, expect, beforeAll } from "vitest";
import { readFileSync, existsSync } from "fs";
import { resolve } from "path";

/**
 * SEO smoke test: sitemap coverage.
 *
 * Verifies that public/sitemap.xml exists, is well-formed XML, contains
 * every must-have public route, and excludes routes that should not be
 * indexed (admin, auth-only, utility pages).
 *
 * Run via `bun run test`. The sitemap is regenerated by the predev/prebuild
 * hooks in package.json, so this test reflects the latest build output.
 */

const SITEMAP_PATH = resolve("public/sitemap.xml");
const BASE_URL = "https://firstaidangel.org";

let xml = "";
let locs: string[] = [];

beforeAll(() => {
  expect(existsSync(SITEMAP_PATH), "public/sitemap.xml is missing — run `bunx tsx scripts/generate-sitemap.ts`").toBe(true);
  xml = readFileSync(SITEMAP_PATH, "utf8");
  locs = Array.from(xml.matchAll(/<loc>([^<]+)<\/loc>/g)).map((m) => m[1]);
});

describe("sitemap.xml structure", () => {
  it("declares the XML prolog and urlset namespace", () => {
    expect(xml.startsWith("<?xml")).toBe(true);
    expect(xml).toContain('xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"');
    expect(xml).toContain("</urlset>");
  });

  it("contains at least 100 URLs", () => {
    expect(locs.length).toBeGreaterThan(100);
  });

  it("uses the production base URL for every entry", () => {
    const bad = locs.filter((l) => !l.startsWith(BASE_URL + "/") && l !== BASE_URL + "/");
    expect(bad, `Non-canonical hosts in sitemap: ${bad.slice(0, 5).join(", ")}`).toEqual([]);
  });

  it("has no duplicate <loc> entries", () => {
    const dupes = locs.filter((l, i) => locs.indexOf(l) !== i);
    expect(dupes, `Duplicate URLs: ${dupes.slice(0, 5).join(", ")}`).toEqual([]);
  });
});

describe("sitemap.xml coverage", () => {
  const required = [
    "/",
    "/kb",
    "/topics",
    "/programs",
    "/cpr",
    "/aed",
    "/aed-finder",
    "/learn",
    "/about",
    "/employer",
    "/personal",
    "/symptoms",
    "/privacy",
    "/terms",
  ];

  it.each(required)("includes required route %s", (path) => {
    expect(locs).toContain(BASE_URL + path);
  });

  const excluded = [
    "/admin",
    "/admin/cms",
    "/auth",
    "/agent",
    "/unsubscribe",
    "/checkout/success",
    "/test-renderer",
    "/style-guide",
  ];

  it.each(excluded)("excludes non-indexable route %s", (path) => {
    expect(locs).not.toContain(BASE_URL + path);
  });
});
