import { Download, FileText } from "lucide-react";
import { useEffect, useState } from "react";
import { useLanguage } from "@/contexts/LanguageContext";
import { translateStrings } from "@/lib/uiTranslate";

interface Props {
  slug: string;
  title: string;
  /** Compact variant for use inside lists/grids. */
  compact?: boolean;
}

/**
 * Download button for the per-topic Angel Action PDF card.
 * PDFs are pre-generated by scripts/generate-angel-action-pdfs.py
 * and served from /angel-action/{slug}.pdf.
 */
const AngelActionDownload = ({ slug, title, compact = false }: Props) => {
  const { language } = useLanguage();
  const [labels, setLabels] = useState({
    heading: "Angel Action Card",
    sub: "Printable A4 quick-reference — perfect for your fridge, first-aid kit or workplace.",
    cta: "Download PDF",
  });

  useEffect(() => {
    if (language === "en") return;
    let cancelled = false;
    translateStrings(language, [
      "Angel Action Card",
      "Printable A4 quick-reference — perfect for your fridge, first-aid kit or workplace.",
      "Download PDF",
    ]).then((s) => {
      if (!cancelled) setLabels({ heading: s[0], sub: s[1], cta: s[2] });
    });
    return () => { cancelled = true; };
  }, [language]);

  const href = `/angel-action/${slug}.pdf`;
  const filename = `${slug}-angel-action.pdf`;

  if (compact) {
    return (
      <a
        href={href}
        download={filename}
        className="inline-flex items-center gap-2 rounded-full bg-primary text-primary-foreground px-4 py-2 text-sm font-semibold shadow-sm hover:bg-primary/90 transition-colors"
        aria-label={`${labels.cta}: ${title}`}
      >
        <Download className="h-4 w-4" />
        {labels.cta}
      </a>
    );
  }

  return (
    <aside className="my-8 rounded-2xl border-2 border-primary/20 bg-gradient-to-br from-primary/5 to-primary/10 p-5 sm:p-6">
      <div className="flex items-start gap-4">
        <div className="flex-shrink-0 w-12 h-12 rounded-xl bg-primary text-primary-foreground flex items-center justify-center shadow-sm">
          <FileText className="h-6 w-6" />
        </div>
        <div className="flex-1 min-w-0">
          <p className="text-[11px] font-bold uppercase tracking-wider text-primary">
            {labels.heading}
          </p>
          <h3 lang={language} className="text-lg font-bold text-foreground mt-0.5">
            {title}
          </h3>
          <p lang={language} className="text-sm text-muted-foreground mt-1 leading-relaxed">
            {labels.sub}
          </p>
          <a
            href={href}
            download={filename}
            className="mt-4 inline-flex items-center gap-2 rounded-full bg-primary text-primary-foreground px-5 py-2.5 text-sm font-semibold shadow-sm hover:bg-primary/90 transition-colors"
          >
            <Download className="h-4 w-4" />
            {labels.cta}
          </a>
        </div>
      </div>
    </aside>
  );
};

export default AngelActionDownload;
